162 list services
pax-app/pax_front_end pull request #8
Opened 2019-10-28 22:02 UTC by fepas

# Descrição
Lista de categorias funcional :)

# Responsáveis pela revisão
@lucasdutraf (PO)

2019-10-29 13:33 UTC, youssef-md requested changes
Não consigo rodar o app, pelo que vi o home_screen.dart tá quebrado

2019-10-30 12:22 UTC, fepas commented
@youssef-md vem cá que tá rolando bolo pra quem aceitar o pr

2019-11-02 22:15 UTC, youssef-md commented
ALELUIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

2019-11-02 22:16 UTC, youssef-md approved these changes

2019-11-02 22:16 UTC, merged